### PR TITLE
refactor!: [DX-1547] Rename Notification and Alert

### PR DESCRIPTION
**Pull request by witwash**
#### Summary

- `OptimusNotification` -> `OptimusAlert` (to match web and design naming)
- `OptimusAlert` -> `OptimusSystemWideBanner`

#### Testing steps

none, refactoring

#### Follow-up issues

none

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by witwash** [comment]
@chaeMil 👀

**Comment by witwash** [comment]
oh, my bad, conflict

**Comment by witwash** [comment]
@chaeMil, ready

**Review by chaeMil — APPROVED** [review]
LGTM

**Pull request merged**
