### PR TITLE
chore: Update Copyright

### PR DESCRIPTION
**Pull request by witwash**
#### Summary

Copyright year update.

#### Testing steps

None

#### Follow-up issues

None.

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Review by chaeMil — APPROVED** [review]

**Comment by witwash** [comment]
@alboiuvlad29 🥺

**Review by alboiuvlad29 — APPROVED** [review]
No 👀

**Comment by alboiuvlad29** [comment]
Thanks for pinging, I wasn't notified

**Comment by witwash** [comment]
No problem. It was outdated for several years, few days would not kill it 😅

**Pull request merged**
