### PR TITLE
feat: [RND-175747] Output tokens in correct format for mobile

### PR DESCRIPTION
**Pull request by riccardoerra**
[RND-175747]

#### Summary

This creates and pushes color tokens for light and dark themes.

Let me know if the format is correct and if you are happy with this Action, https://github.com/MewsSystems/design-tokens/blob/main/.github/workflows/flutter-push.yml, or you want the push to this repo to happen in a different way.

#### Testing steps

None.

#### Follow-up issues

None.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by witwash** [comment]
@riccardoerra, as we discussed previously, we need to format the output of the generated files, so it would pass all checks 🤔

**Comment by riccardoerra** [comment]
> @riccardoerra, as we discussed previously, we need to format the output of the generated files, so it would pass all checks 🤔

@witwash can you tell me more about the format expected?

**Comment by witwash** [comment]
for example here https://github.com/MewsSystems/mews-flutter/blob/c374f87cbebaf8be387066891ac8822a05b80d2a/melos.yaml#L8

I'm running `dart format` on generated `lib/stories/icon/icons_list.dart` file.

**Comment by riccardoerra** [comment]
> for example here
> 
> https://github.com/MewsSystems/mews-flutter/blob/c374f87cbebaf8be387066891ac8822a05b80d2a/melos.yaml#L8
> 
> I'm running `dart format` on generated `lib/stories/icon/icons_list.dart` file.

@witwash maybe I could add something like this, https://dev.to/ravgeetdhillon/setup-github-actions-for-a-dart-project-4aeb, to the action?

**Comment by riccardoerra** [comment]
> Yeah, you might need to run an environment with `dart` in it and run a formatter on those files, before creating an automated PR. We're using `subosito/flutter-action` for our actions. `dart-lang/setup-dart` should be OK. https://github.com/MewsSystems/mews-flutter/blob/c374f87cbebaf8be387066891ac8822a05b80d2a/.github/workflows/check.yml

@witwash I edited the GitHub action, https://github.com/MewsSystems/design-tokens/blob/figma-tokens/.github/workflows/flutter-push.yml,  in order to format the file before pushing theme but your check is still not happy. Maybe I have to configure the linter is a certain way? I added also the pubspec file to repo, https://github.com/MewsSystems/design-tokens/blob/figma-tokens/pubspec.yaml

**Comment by riccardoerra** [comment]
@witwash & @ookami-kb Let me know if you want the files to be pushed to a different folder, if you want them to have a different name and if you want the commit message to be different.

**Comment by witwash** [comment]
@riccardoerra, I think a proper path would be something like `opitmus/lib/src/tokens/` or `optimus/lib/tokens/` with `tokens_<type>.dart` naming scheme for generated files

**Comment by ookami-kb** [comment]
`opitmus/lib/src/tokens/`, I don't think we need to export them.

**Comment by riccardoerra** [comment]
> `opitmus/lib/src/tokens/`, I don't think we need to export them.

@ookami-kb you are suggesting the path should be a different one?

**Comment by riccardoerra** [comment]
> @riccardoerra sorry for confusing message, `opitmus/lib/src/tokens/` is fine, everything inside `src` directory is not exported by default.

@ookami-kb oh ok so I don't need to change that. I'm working right now on fixing why the dark theme tokens are in the wrong format and then I think this is ready to be merged.

**Review by witwash — APPROVED** [review]
LTGM

**Pull request merged**
