### PR TITLE
ci: [DX-1806] Automate package publish on tag

### PR DESCRIPTION
**Pull request by witwash**
#### Summary

- added a workflow to publish `optimus` on tag pushed.

We need to set it up on the other [end](https://dart.dev/tools/pub/automated-publishing#configuring-automated-publishing-from-github-actions-on-pub-dev) to allow this automation.

#### Testing steps

- Create a release and try if it works, after all is set up.

#### Follow-up issues

Tune this workflow and do the same for other packages that need to be published on `pub.dev`

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by witwash** [comment]
@ookami-kb, could you please enable it on the pub.dev admin side? 🙏 
https://dart.dev/tools/pub/automated-publishing#configuring-automated-publishing-from-github-actions-on-pub-dev

**Comment by ookami-kb** [comment]
I would say, it should only run when the new version is merged into master.

**Comment by witwash** [comment]
Do you know if it is supported or I need to do hacks like [this](https://samwize.com/2022/10/28/running-github-action-when-tag-pushed-on-a-specific-branch/)?

**Comment by ookami-kb** [comment]
IIRC, yeah, it requires some hacks. And I'm not sure if this specific solution will work when the tag is first pushed to feature branch, and then merged into master. So let's probably go with environments instead: https://dart.dev/tools/pub/automated-publishing#hardening-security-with-github-deployment-environments

**Comment by witwash** [comment]
@ookami-kb, I believe now you have to set up protection rules for the new environment. I've named it according to the example: `pub.dev`

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
