### PR TITLE
:zap: [RND-49612] Add theming for dialog

### PR DESCRIPTION
**Pull request by Gladkowski**

### CODE REVIEW

**Comment by chaeMil** [comment]
It looks wrong to me.

image

**Comment by Gladkowski** [comment]
@chaeMil fixed ;)

**Comment by ookami-kb** [comment]
@Gladkowski @chaeMil I've pushed some updates, please check. Mainly, I've exported the theme classes (we will need them anyway) + reused them in dialog story.

**Comment by Gladkowski** [comment]
@ookami-kb checked, looks like a valid addition

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
