### PR TITLE
feat(optimus)!: [RND-103480] Add inline dialog [ignore-size]

### PR DESCRIPTION
**Pull request by witwash**
#### Summary

RND-103480

Added a new type of dialog - `OptimusInlineDialog`. Inline dialog is anchored to the widget and is displayed without title and small size only. Interacting outside the dialog will close it. This widget reuses a lot of the components with the default `OptimusDialog`, those parts are now moved outside and are shared between them.

- **[BREAKING CHANGE]** - `NonModalWrapper` is now `DialogWrapper` as it now let's user display `NonModalDialog` and `OptimuInlineDialog`.

<details><summary>Screenshots</summary>
CleanShot 2022-09-08 at 10 55 14@2x
</details> 

#### Testing steps

1. Open Storybook and test that dialog is bounded to the widget.
2. Widget should close on the action button or on tap outside the dialog.

#### Follow-up issues

None

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by witwash** [comment]
@alboiuvlad29 can you please take a look at it?

**Comment by alboiuvlad29** [comment]
It's not working properly in all alignments:

https://user-images.githubusercontent.com/45460964/189934807-3dbde71f-e90c-47b6-9c6d-81ad8dc7e790.mov

I also think it should be centred
image

There should be some examples out there to allow you yo "Shift" the content and preventing it to go outside the bounds.

**Comment by witwash** [comment]
@alboiuvlad29 Yeah, I'm working on it. It's the bug in the Storybook (MediaQuery is giving the whole window size, not counting the sidepanels). It's fine if you are using the device frame and in the real application (doubt that you have layers upon layers upon layers as it is in the Storybook right now).

**Review by alboiuvlad29 — APPROVED** [review]

**Comment by witwash** [comment]
Since we discussed it in Slack, I'd like to mention it here as well. I reworked the position calculation to be retrieved from the overlay, instead of the `MediaQuery.size`

**Comment by witwash** [comment]
@ookami-kb, can you please look at it? 🙏

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
