### PR TITLE
refactor(optimus): Revert changes to `OptimusListTile` and move changes to `OptimusNavListTile`

### PR DESCRIPTION
**Pull request by alboiuvlad29**
#### Summary

Reverts changes to `OptimusListTile` and moves them to `OptimusNavListTile`.

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by alboiuvlad29** [comment]
@witwash Yes that makes sense, but then this should be a different component. The previous functionality has been broken.

**Comment by witwash** [comment]
Basically, the new list tile view was meant to be a separate component. So I've rolled back changes to the `OptimusListTile` and have created a new `OptimusNavListTile` component. There are some new classes for the shared logic otherwise, it's more of a big refactor. No critical changes.

**Comment by alboiuvlad29** [comment]
@witwash The revert and the addition of a component should have been done in 2 different PRs. Either way, LGTM.

**Comment by alboiuvlad29** [comment]
Feel free to review 🙂

**Comment by witwash** [comment]
@ookami-kb,
can you please look at this one? 
it consists of:
- rollback to previous `OptimusListTile`
- rollback to previous `OptimusExpandedListTile`
- added `OptimusNavListTile`
- added a common class for the list tiles and small refactor
- rolled back stories / added new stories for the `OptimusNavListTile`.

**Comment by witwash** [comment]
@ookami-kb,
technically yes, it's a rollback, and `OptimusListTile` has changed back.

**Pull request merged**
