### PR TITLE
fix: Fix dropdown text color

### PR DESCRIPTION
**Pull request by Sevastyan**

### CODE REVIEW

**Review by Gladkowski — APPROVED** [review]
I like this solution. It should be reused all across the lib, replacing `DefaultTextStyle.merge` where possible.

**Review by ookami-kb — CHANGES_REQUESTED** [review]
It breaks the selected text color in light theme mode (the text should be white):

Screenshot 2021-06-22 at 11 11 01

**Comment by Sevastyan** [comment]
@ookami-kb This PR doesn't break the color of the highlighted text, because it has been broken from the beginning. This PR just "highlights" the problem (pun intended).

I think that this PR is worth merging. It objectively makes the situation better, while complying with the presets. Someone can later fix the highlight, cause I don't see an easy solution at the moment.

drop

**Comment by ookami-kb** [comment]
No, it makes the situation worse in the library itself. The screenshot I provided is from optimus storybook. Previously, in the light theme, the highlighted list item had a white color, now it's black. We can discuss possible solution in a call.

**Comment by Sevastyan** [comment]
The pictures I've provided are legit. 

>  in the light theme, the highlighted list item had a white color

is the picture number 2 from the left column (counting starts with 1). So, it **was** (and still is) broken.

**Comment by ookami-kb** [comment]
Take a look at the optimus storybook "Select" page before and after.

**Comment by Sevastyan** [comment]
It is broken in the storybook before:

before

**Comment by ookami-kb** [comment]
Yes, but only subtitle was broken, now the title is broken as well.

**Comment by Sevastyan** [comment]
Well, yes, but the overall it got better, because it is not broken in the dark theme.

**Comment by ookami-kb** [comment]
I cannot call repairing a dark theme by breaking the light theme a "better" overall situation.

**Comment by Sevastyan** [comment]
@ookami-kb I've updated the solution.

**Comment by ookami-kb** [comment]
I don't like that it couples things together and introduces an obscure parameter on `OptimusTypography`. I would rather propose changing `_DropdownItemState`:

```dart
        child: _isHighlighted
            ? OptimusTheme(
                themeMode: ThemeMode.dark,
                darkTheme: OptimusTheme.of(context)
                    .copyWith(brightness: Brightness.dark),
                child: widget.child,
              )
            : widget.child,
```

Basically, we say that highlighted tile has a dark theme – which is true, it's light text on dark background.

**Comment by ookami-kb** [comment]
Please remove `kiosk_mode` files from PR, otherwise LGTM.

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
