### PR TITLE
feat!: Upgrade to DCM 1.13.1

### PR DESCRIPTION
**Pull request by witwash**
#### Summary

Upgrade to DCM 1.13.1

##### Enabled rules:

- [avoid-duplicate-map-keys](https://dcm.dev/docs/rules/common/avoid-duplicate-map-keys)
- [move-variable-outside-iteration](https://dcm.dev/docs/rules/common/move-variable-outside-iteration)
- [avoid-nullable-tostring](https://dcm.dev/docs/rules/common/avoid-nullable-tostring)
- [avoid-duplicate-initializers](https://dcm.dev/docs/rules/common/avoid-duplicate-initializers)
- [avoid-unused-after-null-check](https://dcm.dev/docs/rules/common/avoid-unused-after-null-check)
- [avoid-unassigned-stream-subscriptions](https://dcm.dev/docs/rules/common/avoid-unassigned-stream-subscriptions)
- [avoid-duplicate-collection-elements](https://dcm.dev/docs/rules/common/avoid-duplicate-collection-elements/)

##### Skipped rules:

- [avoid-undisposed-instances](https://dcm.dev/docs/rules/flutter/avoid-undisposed-instances/)

#### Testing steps

None

#### Follow-up issues

None

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by witwash** [comment]
@ookami-kb, should we enable [avoid-duplicate-collection-elements](https://dcm.dev/docs/rules/common/avoid-duplicate-collection-elements/) as well? On one hand, it did find duplicity in the list of strings and that was correct, on the other hand, it might create unnecessary noise with other literals. Overall I rate this rule positively and think we should enable it, but maybe after the update when we could configure this rule.

**Comment by ookami-kb** [comment]
Yeah, let's enable it for a test, I don't think we have a lot of cases of lists with literals.

**Comment by ookami-kb** [comment]
@witwash  Checking it with the main repo. Let's disable [avoid-undisposed-instances](https://dcm.dev/docs/rules/flutter/avoid-undisposed-instances/) for now – too many false positives, e.g. with `Foo()..bar()` and inside `Provider`.

**Comment by witwash** [comment]
@ookami-kb, yeah, I know :D 
my bad, I've enabled [avoid-undisposed-instances](https://dcm.dev/docs/rules/flutter/avoid-undisposed-instances/) instead of the [avoid-undisposed-instances](https://dcm.dev/docs/rules/flutter/avoid-undisposed-instances/) 🤦 
I'm updating it rn

**Comment by witwash** [comment]
@ookami-kb, ready for the review 👍

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
