### PR TITLE
refactor!: Migrate to Flutter 3.10

### PR DESCRIPTION
**Pull request by witwash**
#### Summary

- Migration to `Flutter 3.10`

#### Testing steps

None. Refactor.

#### Follow-up issues

None.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by witwash** [comment]
@ookami-kb, can you please look at it?

**Comment by witwash** [comment]
Also, I see that we have some analysis issues, that lower our score on pub.dev. I'll fix them here as well.

**Comment by witwash** [comment]
@ookami-kb, ping

**Comment by ookami-kb** [comment]
1. I don't think we should update `mews_pedantic` in the same PR as the other libraries. It's the breaking change in the package, let's release it separately.
2. I don't think we should force other libraries to support Dart 3+. It will prevent us from doing fixes until we migrate the apps code to Dart 3+, which will take some time.

**Pull request closed without merging**
