### PR TITLE
feat(optimus): add missing properties

### PR DESCRIPTION
**Pull request by alboiuvlad29**
#### Summary

Add some missing properties for field input.

#### Testing steps

No.

#### Follow-up issues

No.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

### CODE REVIEW

**Comment by alboiuvlad29** [comment]
I'm really not sure why checks fail? 🤔

**Comment by ookami-kb** [comment]
@alboiuvlad29 

```

**Review by witwash — APPROVED** [review]
LGTM

**Review by ookami-kb — APPROVED** [review]

**Comment by alboiuvlad29** [comment]
Oh, I didn't know about that. Thank you @witwash for fixing the formatting. @ookami-kb Would it be better if we add the character limit per project? As in to add the .vscode configuration specifying the line limit:

```json
{
 "editor.rulers": [80],
 "editor.wordWrapColumn": 80
  "dart.lineLength": 80,
}
```

**Comment by ookami-kb** [comment]
@alboiuvlad29 we have it in `tech-mo`, so I don't see any reasons not to add it here as well.

**Pull request merged**
