### PR TITLE
:zap: [RND-43394] Add stack

### PR DESCRIPTION
**Pull request by Gladkowski**

### CODE REVIEW

**Comment by chaeMil** [comment]
image
 I dont know but feels completely broken to me

**Comment by Gladkowski** [comment]
@chaeMil I would say it's an expected behavior. If the `orientation: horizontal`, and `distribution: stretch`,  `main axis` changes would not have visual impact, since the items are stretched. For the `cross axis` case I've just added stack items with different height to make gravity changes visible.

**Comment by chaeMil** [comment]
> @chaeMil I would say it's an expected behavior. If the `orientation: horizontal`, and `distribution: stretch`, `main axis` changes would not have visual impact, since the items are stretched. For the `cross axis` case I've just added stack items with different heights to make gravity changes visible.

Ok but the main problem i have is when you have `breakpoint` set to `medium` or lower and change `direction`, then its not doing anything. Its seems weird to me and the documentation is really vague about this.

**Review by chaeMil — APPROVED** [review]

**Comment by ookami-kb** [comment]
@chaeMil @Gladkowski I've pushed some changes, please review.

**Comment by Gladkowski** [comment]
> @chaeMil @Gladkowski I've pushed some changes, please review.

Checked. Nice code reduction.

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
