### PR TITLE
feat(optimus)!: Update icons

### PR DESCRIPTION
**Pull request by Gladkowski**
#### Summary

I have manually removed all duplicated resources in svg font provided by design team.
Add new icons | [Optimus](https://mews.design/7b4bb574e/p/038eb3-icons)

### CODE REVIEW

**Review by Sevastyan — CHANGES_REQUESTED** [review]
Please, describe how you have generated the file `OptimusIcons.ttf`. There are a lot of entry points that point to addresses that contain nothing. The ones that are useful are only lines ` 536` through `1052`.

Also, the following point to nothing:
`chevron_up_1`
`chevron_down_1`
`profile_1`.

**Comment by Gladkowski** [comment]
> Please, describe how you have generated the file `OptimusIcons.ttf`. There are a lot of entry points that point to addresses that contain nothing. The ones that are useful are only lines ` 536` through `1052`.
> 
> Also, the following point to nothing:
> `chevron_up_1`
> `chevron_down_1`
> `profile_1`.

The icons were generated by www.fluttericon.com .

**Comment by Sevastyan** [comment]
> The icons were generated by www.fluttericon.com .

I'm afraid that doesn't answer my question.

>  Every item represents existing icon from the font.

I'm not sure about that. Try any icon that I've rendered as useless and non-existent.

There are basically 592 icons defined in the font. Other data points are fake.

**Comment by Sevastyan** [comment]
You can even see it in the `storybook` - the Select doesn't contain the chevron.

**Comment by Gladkowski** [comment]
> > Please, describe how you have generated the file `OptimusIcons.ttf`. There are a lot of entry points that point to addresses that contain nothing. The ones that are useful are only lines ` 536` through `1052`.
> > Also, the following point to nothing:
> > `chevron_up_1`
> > `chevron_down_1`
> > `profile_1`.
> 
> The icons were generated by [www.fluttericon.com](http://www.fluttericon.com) .



> You can even see it in the `storybook` - the Select doesn't contain the chevron.

you are correct, the issue is with svg font. I'll contact designers

**Review by Sevastyan — APPROVED** [review]
* Glyphs' names are messed up now: previously they had proper names, now they have Unicode address points instead.
* Make sure, that this is marked as a BREAKING CHANGE. Most of the names of icons have changed now, and our apps are affected:

Commander:
```
lib/main/widgets/main_screen.dart:132:33: Error: Getter not found: 'summary_order_4'.
        icon: Icon(OptimusIcons.summary_order_4, size: 24),
                                ^^^^^^^^^^^^^^^
```

Kiosk:

```
lib/src/core/presentation/keyboard/kiosk_select_input.dart:132:24: Error: Getter not found: 'chevron_down_1'.
          OptimusIcons.chevron_down_1,
                       ^^^^^^^^^^^^^^
lib/src/session/presentation/check_in/registration_card/widgets/fields/copy_address_button_field.dart:60:32: Error: Getter not found: 'profile_1'.
        leftIcon: OptimusIcons.profile_1,
                               ^^^^^^^^^
```

But in general, LGTM

**Pull request merged**
